---
- name: "RETRIEVE DEVICE ATTRIBUTES"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"

  tasks:
    - name: "API CALL TO GET DEVICES"
      ansible.builtin.include_tasks: "tasks/task_get_devices.yml"

    - name: "GENERATE INVENTORY"
      ansible.builtin.include_tasks: "tasks/task_generate_inventory.yml"

- name: "RETRIEVE ATTRIBUTES PER DEVICE"
  hosts: "devices"
  connection: "network_cli"
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"

  tasks:
    - name: "API CALL TO GET DEVICE ATTRIBUTES"
      ansible.builtin.include_tasks: "tasks/task_get_device_attributes.yml"
      loop: "{{ attributes | dict2items }}"
      loop_control:
        loop_var: "attribute"
        label: "{{ attribute ['key'] }}"

    - name: "DEBUG DEVICE ATTRIBUTES"
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname] }}"
      when: ( 'edge' in inventory_hostname )
