---
- name: "PULL DATA AND RENDER CONFIGS"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"

  tasks:
    # - name: "API CALL TO GET LOCATIONS"
    #   ansible.builtin.include_tasks: "tasks/task_get_locations.yml"

    # - name: "API CALL TO GET PROTOCOLS"
    #   ansible.builtin.include_tasks: "tasks/task_get_protocols.yml"

    - name: "API CALL TO GET DEVICES"
      ansible.builtin.include_tasks: "tasks/task_get_devices.yml"
