---
- name: "PLAY - GET ITEMS FROM NETBOX SOT "
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    grapghql_url: "http://192.168.2.201:8800/graphql/"
    api_url: "http://192.168.2.201:8800/api"

  tasks:
    - name: "SET_FACT QUERY STRING"
      ansible.builtin.set_fact:
        query_string: |
          query {
            device_list {
              hostname: name
              role {
                name
              }
              bgpsession_set {
                remote_as {
                  asn
                }
                remote_address {
                  address
                }
                custom_fields
              }
              primary_ip4 {
                address
              }
              platform {
                name
              }
              device_type {
                manufacturer {
                  name
                }
              }
              interfaces {
                name
                enabled
                vrf {
                  name
                }
                description
                ip_addresses {
                  address
                }
                custom_fields
              }
              config_context
            }
          }

    - name: "RETRIEVE DATA FROM GRAPHQL API"
      ansible.builtin.uri:
        url: "{{ grapghql_url }}"
        method: POST
        headers:
          content-type: "application/json"
          Authorization: Token abc779e1f81ecebf1a32ad0b94d253672b801470
        body_format: json
        body:
          query: "{{ query_string }}"
      connection: local
      register: graphql_result

    - name: "GENERATE INVENTORY"
      ansible.builtin.include_tasks: "tasks/task_generate_inventory_netbox.yml"
      vars:
        device_list: "{{ graphql_result['json']['data']['device_list'] }}"

- name: "PLAY: RENDER DEVICE CONFIGURATION"
  hosts: "devices"
  connection: "network_cli"
  gather_facts: false

  tasks:
    - name: "10: RENDER DEVICE CONFIGURATION"
      ansible.builtin.template:
        src: "templates/netbox/{{ role }}.j2"
        dest: "configs/netbox/{{ inventory_hostname }}.cfg"
      delegate_to: "localhost"
