---
- name: "RETRIEVE DEVICE ATTRIBUTES"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"

  tasks:
    - name: "TASK GET ENDPOINTS OBJECTS IN SOT"
      ansible.builtin.include_role:
        name: "ansible_role_sot_operations"
        tasks_from: "task_get_request"
      vars:
        endpoint: "devices"

    - name: "GENERATE INVENTORY"
      ansible.builtin.include_tasks: "tasks/task_generate_inventory.yml"
      vars:
        api_response_devices: "{{ api_response }}"

- name: "RETRIEVE ATTRIBUTES PER DEVICE"
  hosts: "devices"
  connection: "network_cli"
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"

  tasks:
    - name: "10: GET DEVICE ATTRIBUTES"
      ansible.builtin.include_tasks: "tasks/task_get_device_attributes.yml"
      loop: "{{ attributes | dict2items }}"
      loop_control:
        loop_var: "attribute"
        label: "{{ attribute['key'] }}"

    - name: "20: DEBUG DEVICE ATTRIBUTES"
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname] }}"
      delegate_to: "localhost"
      tags:
        - "debug"

    - name: "20: RENDER DEVICE CONFIGURATION"
      ansible.builtin.template:
        src: "templates/{{ ansible_network_os }}/{{ scope }}.j2"
        dest: "configs/{{ inventory_hostname }}.cfg"
      delegate_to: "localhost"

    - name: "APPLY CONFIG"
      napalm.napalm.napalm_install_config:
        dev_os: "ios"
        config_file: "configs/{{ inventory_hostname }}.cfg"
        commit_changes: true
        replace_config: false

    - name: "UPDATE DEVICE NETWORK SOT STATUS"
      ansible.builtin.include_tasks: "tasks/task_update_device_status.yml"
      vars:
        device_status: "Go Live"
