---
- name: "PLAY - USE INVENTORY PLUGIN"
  hosts: "localhost"
  gather_facts: false

  vars:
    local_serial_number: "{{ serial_number }}"

  tasks:
    - name: "FIND HOSTNAME"
      ansible.builtin.debug:
        msg: "{{ local_serial_number }}"

    - name: "FIND HOSTNAME FROM SERIAL NUMBER"
      ansible.builtin.set_fact:
        devices:
          hostvars: "{{ hostvars }}"

    - name: "FIND SJON QUERY"
      ansible.builtin.set_fact:
        device: "{{ devices | community.general.json_query(set_query) }}"
      vars:
        set_query: "to_array(hostvars.*)[?serial_number == '{{ local_serial_number }}'].inventory_hostname | [0]"

    - name: "DEBUG HOSTNAME"
      ansible.builtin.debug:
        msg: "{{ device }}"

- name: "PLAY - USE INVENTORY PLUGIN"
  hosts: "{{ hostvars['localhost']['device'] }}"
  gather_facts: false

  tasks:
    - name: "5: INCLUDE TASK TO GET BGP SETTINGS"
      ansible.builtin.include_tasks: "tasks/task.get_device_attributes.yml"
      when: role.name | split(':') | last == 'router'

    # - name: "10: BUILD INIT CONFIG"
    #   ansible.builtin.template:
    #     src: "templates/{{ platform.name }}/{{ platform.name }}.j2"
    #     dest: "configs/{{ inventory_hostname }}.cfg"
    #   delegate_to: localhost

    - name: "APPLY CONFIG IOL DEVICES"
      cisco.ios.ios_config:
        src: "templates/{{ platform.name }}/{{ platform.name }}.j2"
        replace: block
      when: ( platform.name == "ios" )
