---
- name: "PLAY - USE INVENTORY PLUGIN"
  hosts: "Branch, ISP"
  gather_facts: false

  tasks:
    - name: "5: INCLUDE TASK TO GET BGP SETTINGS"
      ansible.builtin.include_tasks: "tasks/task.get_device_attributes.yml"
      when: role.name | split(':') | last == 'router'

    # - name: "10: BUILD INIT CONFIG"
    #   ansible.builtin.template:
    #     src: "templates/{{ platform.name }}/{{ platform.name }}.j2"
    #     dest: "configs/{{ inventory_hostname }}.cfg"
    #   delegate_to: localhost

    - name: "APPLY CONFIG IOL DEVICES"
      cisco.ios.ios_config:
        src: "templates/{{ platform.name }}/{{ platform.name }}.j2"
      when: ( platform.name == "ios" )
