---
- name: "PLAY - GET ITEM FROM NETWORK SOT"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    api_url: "http://192.168.2.201:8000"
    endpoint: "interfaces"
    id: "651f8724a5e098e62533d594"

  tasks:
    - name: "TASK GET ENDPOINTS OBJECTS IN SOT"
      ansible.builtin.include_role:
        name: "ansible_role_sot_operations"
        tasks_from: "task_get_request_by_id"

    - name: "SET FACT ENDPOINT ATTRIBUTES"
      ansible.builtin.set_fact:
        output_file:
          endpoint_list: "{{ [api_response['json']] }}"

    - name: "TASK - SAVE ATTRIBUTES ON FILES"
      ansible.builtin.template:
        src: "templates/attributes/endpoint_attributes.j2"
        dest: "output/{{ api_response['json']['_id'] }}.yml"
