---
- name: "GENERATE DEVICE INVENTORY"
  ansible.builtin.add_host:
    name: "{{ device['hostname'] }}"
    ansible_host: "{{ device['primary_ip4']['address'] | ansible.utils.ipaddr('address') }}"
    ansible_user: "admin"
    ansible_password: "admin"
    groups: "devices"
    ansible_network_os: "{{ device['platform']['name'] }}"
    role: "{{ device['role']['name'] }}"
    attributes: "{{ device }}"
  loop: "{{ device_list }}"
  loop_control:
    loop_var: device
    label: "{{ device['hostname'] }}"
  when:
    - device['platform']['name'] == 'cisco.ios.ios'
    - device['role']['name'] in ['edge', 'provider_edge']
