---
- name: "SET_FACT QUERY STRING"
  ansible.builtin.set_fact:
    query_string: "{{ lookup('ansible.builtin.file', 'vars/graphql/bgp_peerings.gql') }}"
  delegate_to: "localhost"
  run_once: true

- name: "RETRIEVE BGP PEERINGS GRAPHQL API"
  ansible.builtin.uri:
    url: "{{ grapghql_url }}"
    method: POST
    headers:
      content-type: "application/json"
      Authorization: Token 85a79dc466d6b3e7e581b264b13adb9f3595f60c
    body_format: json
    body:
      query: "{{ query_string }}"
      variables:
        {
          "device_name": "{{ inventory_hostname }}"
        }
    validate_certs: false
  delegate_to: localhost
  register: result
  vars:
    grapghql_url: "https://192.168.2.201:445/api/graphql/"


- name: "SET_FACT BGP SETTINGS"
  ansible.builtin.set_fact:
    bgp: "{{ result['json']['data'] }}"
