---
- name: "20: INITIALIZE API RESPONSE ATTRIBUTES VAR"
  ansible.builtin.set_fact:
    api_response_attributes: []
  delegate_to: localhost

- name: "10: TASK GET ENDPOINT OBJECTS IN SOT BY ID"
  ansible.builtin.include_tasks: "task_get_attributes_list.yml"
  loop: "{{ attribute['value'] }}"
  loop_control:
    loop_var: "attribute_name"
    label: "{{ attribute_name['name'] }}"

- name: "20: SET_FACT DEVICE ATTRIBUTE"
  ansible.builtin.set_fact:
    "{{ attribute['key'] }}": "{{ api_response_attributes }}"
  delegate_to: localhost
