---
- name: "API CALL TO ADD NEW DEVICES"
  ansible.builtin.uri:
    url: "{{ api_url }}/api/devices"
    method: POST
    body: "{{ device }}"
    status_code: 201
    body_format: json
  loop: "{{ devices }}"
  loop_control:
    loop_var: "device"
    label: "{{ device['hostname'] }}"
  register: api_response_devices

- name: "DEBUG RESULTS"
  ansible.builtin.debug:
    msg: "{{ api_response_devices }}"
