---
- name: "UPDATE DEVICE NETWORK SOT STATUS"
  ansible.builtin.include_role:
    name: "ansible_role_sot_operations"
    tasks_from: "task_put_request"
  vars:
    endpoint: "devices"
    endpoint_list:
      - id: "{{ device_id }}"
        status: "{{ device_status }}"
