---
- name: "BLOCK OF GET REQUESTS"
  block:
    - name: "10: TASK GET ENDPOINT OBJECTS IN SOT BY ID"
      ansible.builtin.include_role:
        name: "ansible_role_sot_operations"
        tasks_from: "task_get_request_by_id"
      vars:
        endpoint: "{{ attribute['key'] }}"
        id: "{{ attribute_name['id'] }}"

    - name: "20: SET_FACT DEVICE ATTRIBUTES"
      ansible.builtin.set_fact:
        api_response_attributes: "{{ api_response_attributes | default([]) + [api_response['json']] }}"
      delegate_to: localhost
