---
- name: "API CALL TO ADD NEW LOCATION"
  ansible.builtin.uri:
    url: "{{ api_url }}/api/locations"
    method: POST
    body: "{{ location }}"
    status_code: 201
    body_format: json
  loop: "{{ locations }}"
  loop_control:
    label: "{{ location['site'] }}"
    loop_var: "location"
  register: api_response_locations

- name: "DEBUG RESULTS"
  ansible.builtin.debug:
    msg: "{{ api_response_locations }}"
