query ($device_name: [String]) {
  bgp_peerings (device: $device_name) {
    endpoints{
      peer{
        routing_instance {
          device {
            name
          }
        }
      }
      address_families{
        afi_safi
        extra_attributes
      }
      description
      source_ip {
        address
      }
      autonomous_system{
        asn
      }
      }
    status {
      name
    }
    }
}
